[package]
name = "hello-async-std-macro"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hi = { path = "../hi", features = ["async-std"] }
async-std = { version = "1", features = ["attributes"]}