[package]
name = "hello-tokio-macro"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hi = { path = "../hi", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"]}